import * as ExcelJS from 'exceljs';
import { format } from 'date-fns';
import type { ComplianceReportData } from './complianceEngine';

// Brand colors - exact values from design spec
const NAVY = '0F172A';      // #0F172A
const INDIGO = '4338CA';    // #4338CA
const BLUE = '2563EB';      // #2563EB
const WHITE = 'FFFFFF';
const LIGHT_BG = 'F8FAFC';  // #F8FAFC
const PROFIT_GREEN = '16A34A';  // #16A34A
const LOSS_RED = 'DC2626';      // #DC2626
const NEUTRAL_BLUE = '2563EB';  // #2563EB
const DARK_GRAY = '374151';     // #374151
const MEDIUM_GRAY = '64748B';   // #64748B
const BORDER_GRAY = 'D1D5DB';
const HEADER_FONT_SIZE = 14;
const BODY_FONT_SIZE = 10;
const SMALL_FONT_SIZE = 9;

/**
 * Builds the institutional-grade Annual Compliance Report Excel Workbook with 8 sheets:
 * Overview, Executive Summary, Account Information, Trading Ledger, Strategy Analysis,
 * Financial Summary, Audit Trail, Data Integrity.
 */
export async function exportAnnualComplianceReportExcel(data: ComplianceReportData): Promise<ExcelJS.Workbook> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'AI Trade Journal';
  workbook.title = 'Annual Compliance Report';
  workbook.description = 'Annual Compliance Report generated by AI Trade Journal';
  workbook.created = new Date(data.metadata.exportTimestampUTC);

  /**
   * Apply branded header styling to a row
   */
  const applyBrandHeader = (row: ExcelJS.Row, height = 30) => {
    row.font = { bold: true, size: HEADER_FONT_SIZE, color: { argb: WHITE }, name: 'Calibri' };
    row.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: NAVY } };
    row.height = height;
  };

  /**
   * Apply sub-header styling (column headers)
   */
  const applySubHeader = (row: ExcelJS.Row, count: number) => {
    row.font = { bold: true, size: BODY_FONT_SIZE, color: { argb: WHITE }, name: 'Calibri' };
    row.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: NAVY } };
    row.height = 22;
    for (let c = 1; c <= count; c++) {
      const cell = row.getCell(c);
      cell.border = {
        top: { style: 'thin', color: { argb: BORDER_GRAY } },
        bottom: { style: 'thin', color: { argb: BORDER_GRAY } },
        left: { style: 'thin', color: { argb: BORDER_GRAY } },
        right: { style: 'thin', color: { argb: BORDER_GRAY } },
      };
      cell.alignment = { vertical: 'middle', horizontal: 'center' };
    }
  };

  /**
   * Style a data row with alternating background and borders
   */
  const styleDataRow = (row: ExcelJS.Row, idx: number, colCount: number) => {
    if (idx % 2 === 0) {
      row.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: LIGHT_BG } };
    }
    for (let c = 1; c <= colCount; c++) {
      const cell = row.getCell(c);
      cell.font = { size: BODY_FONT_SIZE, name: 'Calibri' };
      cell.border = {
        top: { style: 'thin', color: { argb: BORDER_GRAY } },
        bottom: { style: 'thin', color: { argb: BORDER_GRAY } },
        left: { style: 'thin', color: { argb: BORDER_GRAY } },
        right: { style: 'thin', color: { argb: BORDER_GRAY } },
      };
      cell.alignment = { vertical: 'middle', wrapText: false };
    }
  };

  /**
   * Add a section header row
   */
  const addSectionHeader = (ws: ExcelJS.Worksheet, rowNum: number, text: string) => {
    const row = ws.getRow(rowNum);
    row.font = { bold: true, size: 11, color: { argb: WHITE }, name: 'Calibri' };
    row.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: NAVY } };
    row.getCell(1).value = text;
    row.height = 22;
    return row;
  };

  // ===================================================================
  // SHEET 1: OVERVIEW
  // ===================================================================
  const overview = workbook.addWorksheet('Overview');
  overview.properties.tabColor = { argb: NAVY };

  // Columns: A=Label, B=Value
  overview.columns = [
    { width: 35 },
    { width: 55 },
  ];

  // Brand header
  const brandRow1 = overview.addRow(['ANNUAL COMPLIANCE REPORT']);
  applyBrandHeader(brandRow1, 35);
  overview.mergeCells('A1:B1');
  brandRow1.getCell(1).alignment = { horizontal: 'center', vertical: 'middle' };

  const subRow1 = overview.addRow(['Official Financial Record — AI Trade Journal']);
  subRow1.font = { italic: true, size: 11, color: { argb: MEDIUM_GRAY }, name: 'Calibri' };
  overview.mergeCells('A2:B2');
  subRow1.getCell(1).alignment = { horizontal: 'center' };

  overview.addRow([]);

  // Report Metadata section
  addSectionHeader(overview, 4, 'REPORT METADATA');

  const metaRows = [
    ['Report ID', data.metadata.reportId],
    ['Report Type', 'Annual Compliance Report (Official Financial Record)'],
    ['Generated (UTC)', format(new Date(data.metadata.exportTimestampUTC), 'yyyy-MM-dd HH:mm:ss')],
    ['Time Zone', data.metadata.timeZone || 'UTC'],
    ['User ID', data.metadata.userId || 'N/A'],
    ['Account ID', data.metadata.accountId || 'N/A'],
    ['Export Version', data.metadata.exportVersion],
    ['Reporting Period Start', data.metadata.reportingPeriodStart ? format(new Date(data.metadata.reportingPeriodStart), 'yyyy-MM-dd') : 'N/A'],
    ['Reporting Period End', data.metadata.reportingPeriodEnd ? format(new Date(data.metadata.reportingPeriodEnd), 'yyyy-MM-dd') : 'N/A'],
  ];

  metaRows.forEach((rowData, idx) => {
    const row = overview.addRow(rowData);
    styleDataRow(row, idx, 2);
    row.getCell(1).font = { bold: true, size: BODY_FONT_SIZE, name: 'Calibri', color: { argb: DARK_GRAY } };
  });

  // Financial Summary section
  const finStartRow = metaRows.length + 6;
  overview.addRow([]);
  addSectionHeader(overview, finStartRow, 'FINANCIAL SUMMARY');

  const finSummaryRows = [
    ['Gross Profit', `$${(data.financialSummary.grossProfit || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}`],
    ['Gross Loss', `($${(data.financialSummary.grossLoss || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })})`],
    ['Net Profit', `$${(data.financialSummary.netProfit || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}`],
    ['Total Fees', `$${(data.financialSummary.totalFees || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}`],
    ['Net After Fees', `$${(data.financialSummary.netAfterFees || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}`],
    ['Average Trade', `$${(data.financialSummary.averageTrade || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}`],
    ['Profit Factor', data.financialSummary.profitFactor === Infinity ? '∞' : (data.financialSummary.profitFactor || 0).toFixed(2)],
    ['Win Rate', `${(data.financialSummary.winRate || 0).toFixed(2)}%`],
  ];

  finSummaryRows.forEach((rowData, idx) => {
    const row = overview.addRow(rowData);
    styleDataRow(row, idx, 2);
    row.getCell(1).font = { bold: true, size: BODY_FONT_SIZE, name: 'Calibri', color: { argb: DARK_GRAY } };

    // Color code values
    const label = rowData[0];
    if (['Gross Profit', 'Net Profit', 'Net After Fees'].includes(label)) {
      const val = parseFloat(rowData[1].replace(/[$,()]/g, '') || '0');
      row.getCell(2).font = { bold: true, size: BODY_FONT_SIZE, name: 'Calibri', color: { argb: val >= 0 ? PROFIT_GREEN : LOSS_RED } };
    } else if (label === 'Gross Loss') {
      row.getCell(2).font = { bold: true, size: BODY_FONT_SIZE, name: 'Calibri', color: { argb: LOSS_RED } };
    } else if (['Total Fees', 'Average Trade', 'Profit Factor', 'Win Rate'].includes(label)) {
      row.getCell(2).font = { size: BODY_FONT_SIZE, name: 'Calibri', color: { argb: NEUTRAL_BLUE } };
    }
  });

  // Data Integrity section
  const diStartRow = finStartRow + finSummaryRows.length + 3;
  overview.addRow([]);
  addSectionHeader(overview, diStartRow, 'DATA INTEGRITY');

  const integrityRows = [
    ['SHA-256 Hash', data.dataIntegrity.sha256Hash || 'N/A'],
    ['Checksum', data.dataIntegrity.checksum || 'N/A'],
    ['Record Verification Count', (data.dataIntegrity.recordVerificationCount || 0).toString()],
    ['Generation Timestamp', data.dataIntegrity.generationTimestamp ? format(new Date(data.dataIntegrity.generationTimestamp), 'yyyy-MM-dd HH:mm:ss') + ' UTC' : 'N/A'],
  ];

  integrityRows.forEach((rowData, idx) => {
    const row = overview.addRow(rowData);
    styleDataRow(row, idx, 2);
    row.getCell(1).font = { bold: true, size: BODY_FONT_SIZE, name: 'Calibri', color: { argb: DARK_GRAY } };
  });

  // Freeze panes
  overview.views = [{ state: 'frozen', xSplit: 0, ySplit: 4 }];

  // ===================================================================
  // SHEET 2: EXECUTIVE SUMMARY
  // ===================================================================
  const execSummary = workbook.addWorksheet('Executive Summary');
  execSummary.properties.tabColor = { argb: INDIGO };

  const execCols = [
    { width: 25 },
    { width: 25 },
    { width: 25 },
    { width: 25 },
    { width: 25 },
  ];
  execSummary.columns = execCols;

  // Brand header
  const execBrand = execSummary.addRow(['EXECUTIVE SUMMARY']);
  applyBrandHeader(execBrand, 35);
  execSummary.mergeCells('A1:E1');
  execBrand.getCell(1).alignment = { horizontal: 'center', vertical: 'middle' };

  const execSub = execSummary.addRow(['Key Performance Metrics — Annual Compliance Report']);
  execSub.font = { italic: true, size: 11, color: { argb: MEDIUM_GRAY }, name: 'Calibri' };
  execSummary.mergeCells('A2:E2');
  execSub.getCell(1).alignment = { horizontal: 'center' };
  execSummary.addRow([]);

  // Metrics in a grid layout (2 rows of 5 columns)
  const metricHeaders = ['Metric', 'Value', 'Metric', 'Value', ''];
  const metricHeaderRow = execSummary.addRow(metricHeaders);
  applySubHeader(metricHeaderRow, 5);
  execSummary.mergeCells('A4:B4');
  execSummary.mergeCells('C4:D4');
  // Actually, let's do a simple key-value layout for clarity
  // Re-do: clear and add properly
  execSummary.getRow(4).getCell(1).value = 'METRIC';
  execSummary.getRow(4).getCell(2).value = 'VALUE';
  execSummary.getRow(4).getCell(3).value = 'METRIC';
  execSummary.getRow(4).getCell(4).value = 'VALUE';

  const metricsLeft = [
    { label: 'Total Trades', value: data.accountSummary.totalTrades.toString(), color: NAVY },
    { label: 'Gross Profit', value: `$${(data.accountSummary.grossProfit || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}`, color: PROFIT_GREEN },
    { label: 'Gross Loss', value: `$${(data.accountSummary.grossLoss || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}`, color: LOSS_RED },
    { label: 'Net P&L', value: `$${(data.accountSummary.netPnl || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}`, color: data.accountSummary.netPnl >= 0 ? PROFIT_GREEN : LOSS_RED },
    { label: 'Profit Factor', value: data.accountSummary.profitFactor === Infinity ? '∞' : (data.accountSummary.profitFactor || 0).toFixed(2), color: INDIGO },
  ];

  const metricsRight = [
    { label: 'Win Rate', value: `${(data.accountSummary.winRate || 0).toFixed(2)}%`, color: NEUTRAL_BLUE },
    { label: 'Average Trade', value: `$${(data.accountSummary.averageTrade || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}`, color: DARK_GRAY },
    { label: 'Largest Win', value: `$${(data.accountSummary.largestWin || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}`, color: PROFIT_GREEN },
    { label: 'Largest Loss', value: `$${(data.accountSummary.largestLoss || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}`, color: LOSS_RED },
    { label: 'Trading Days', value: (data.accountSummary.tradingDays || 0).toString(), color: DARK_GRAY },
  ];

  // Additional row for Avg Daily P&L
  const extraLeft = { label: 'Avg Daily P&L', value: `$${(data.accountSummary.averageDailyPnl || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}`, color: INDIGO };

  metricsLeft.forEach((m, idx) => {
    const rowIdx = 5 + idx;
    const row = execSummary.getRow(rowIdx);
    row.getCell(1).value = m.label;
    row.getCell(1).font = { bold: true, size: BODY_FONT_SIZE, name: 'Calibri', color: { argb: DARK_GRAY } };
    row.getCell(2).value = m.value;
    row.getCell(2).font = { bold: true, size: BODY_FONT_SIZE, name: 'Calibri', color: { argb: m.color } };

    if (metricsRight[idx]) {
      const mr = metricsRight[idx];
      row.getCell(3).value = mr.label;
      row.getCell(3).font = { bold: true, size: BODY_FONT_SIZE, name: 'Calibri', color: { argb: DARK_GRAY } };
      row.getCell(4).value = mr.value;
      row.getCell(4).font = { bold: true, size: BODY_FONT_SIZE, name: 'Calibri', color: { argb: mr.color } };
    }

    styleDataRow(row, idx, 5);
    row.height = 22;
  });

  // Add Avg Daily P&L
  const extraRowIdx = 5 + metricsLeft.length;
  const extraRow = execSummary.getRow(extraRowIdx);
  extraRow.getCell(1).value = extraLeft.label;
  extraRow.getCell(1).font = { bold: true, size: BODY_FONT_SIZE, name: 'Calibri', color: { argb: DARK_GRAY } };
  extraRow.getCell(2).value = extraLeft.value;
  extraRow.getCell(2).font = { bold: true, size: BODY_FONT_SIZE, name: 'Calibri', color: { argb: extraLeft.color } };
  styleDataRow(extraRow, 0, 5);
  extraRow.height = 22;

  execSummary.views = [{ state: 'frozen', xSplit: 0, ySplit: 4 }];

  // ===================================================================
  // SHEET 3: ACCOUNT INFORMATION
  // ===================================================================
  const acctInfo = workbook.addWorksheet('Account Information');
  acctInfo.properties.tabColor = { argb: NAVY };
  acctInfo.columns = [
    { width: 30 },
    { width: 60 },
  ];

  const acctBrand = acctInfo.addRow(['ACCOUNT INFORMATION']);
  applyBrandHeader(acctBrand, 35);
  acctInfo.mergeCells('A1:B1');
  acctBrand.getCell(1).alignment = { horizontal: 'center', vertical: 'middle' };
  acctInfo.addRow([]);

  addSectionHeader(acctInfo, 4, 'ATTRIBUTE');
  acctInfo.getRow(4).getCell(1).value = 'ATTRIBUTE';
  acctInfo.getRow(4).getCell(2).value = 'VALUE';

  const acctFields = [
    ['Account ID', data.accountInfo.accountId || 'N/A'],
    ['User ID', data.accountInfo.userId || 'N/A'],
    ['Export Timestamp', `${format(new Date(data.accountInfo.exportTimestamp), 'yyyy-MM-dd HH:mm:ss')} UTC`],
    ['Reporting Period', data.accountInfo.reportingPeriod],
    ['Time Zone', data.accountInfo.timeZone || 'UTC'],
    ['Report Version', data.accountInfo.reportVersion],
    ['Data Source', data.accountInfo.dataSource],
  ];

  acctFields.forEach((rowData, idx) => {
    const row = acctInfo.addRow(rowData);
    styleDataRow(row, idx, 2);
    row.getCell(1).font = { bold: true, size: BODY_FONT_SIZE, name: 'Calibri', color: { argb: DARK_GRAY } };
  });

  acctInfo.views = [{ state: 'frozen', xSplit: 0, ySplit: 4 }];

  // ===================================================================
  // SHEET 4: TRADING LEDGER
  // ===================================================================
  const ledger = workbook.addWorksheet('Trading Ledger');
  ledger.properties.tabColor = { argb: NAVY };

  ledger.columns = [
    { header: 'Trade ID', key: 'tradeId', width: 14 },
    { header: 'Symbol', key: 'symbol', width: 10 },
    { header: 'Market', key: 'market', width: 10 },
    { header: 'Entry Date', key: 'entryDate', width: 14 },
    { header: 'Exit Date', key: 'exitDate', width: 14 },
    { header: 'Side', key: 'side', width: 8 },
    { header: 'Quantity', key: 'quantity', width: 12 },
    { header: 'Entry', key: 'entryPrice', width: 12 },
    { header: 'Exit', key: 'exitPrice', width: 12 },
    { header: 'Fees', key: 'fees', width: 12 },
    { header: 'Net P&L', key: 'netPnl', width: 14 },
  ];

  const ledgerBrandRow = ledger.addRow(['ANNUAL COMPLIANCE REPORT — TRADING LEDGER']);
  applyBrandHeader(ledgerBrandRow, 30);
  ledger.mergeCells('A1:K1');
  ledgerBrandRow.getCell(1).alignment = { horizontal: 'center', vertical: 'middle' };

  ledger.addRow([]);

  // Column headers at row 3
  const ledgerHeaderRow = ledger.getRow(3);
  applySubHeader(ledgerHeaderRow, 11);

  data.ledger.forEach((t, idx) => {
    const row = ledger.addRow({
      tradeId: t.tradeId || '',
      symbol: t.assetSymbol || '',
      market: t.market || '',
      entryDate: t.entryDate ? format(new Date(t.entryDate), 'yyyy-MM-dd') : '',
      exitDate: t.exitDate ? format(new Date(t.exitDate), 'yyyy-MM-dd') : '',
      side: t.positionType || '',
      quantity: t.quantity || 0,
      entryPrice: t.entryPrice || 0,
      exitPrice: t.exitPrice || 0,
      fees: t.fees || 0,
      netPnl: t.netPnl || 0,
    });

    styleDataRow(row, idx, 11);

    // Number formatting
    row.getCell('quantity').numFmt = '#,##0';
    row.getCell('entryPrice').numFmt = '#,##0.00';
    row.getCell('exitPrice').numFmt = '#,##0.00';
    row.getCell('fees').numFmt = '#,##0.00';
    row.getCell('netPnl').numFmt = '#,##0.00';

    // Color Net P&L
    const netPnl = t.netPnl || 0;
    row.getCell('netPnl').font = {
      bold: true,
      size: BODY_FONT_SIZE,
      name: 'Calibri',
      color: { argb: netPnl >= 0 ? PROFIT_GREEN : LOSS_RED },
    };

    // Color side
    const side = (t.positionType || '').toUpperCase();
    if (side === 'BUY' || side === 'LONG') {
      row.getCell('side').font = { bold: true, size: BODY_FONT_SIZE, name: 'Calibri', color: { argb: PROFIT_GREEN } };
    } else if (side === 'SELL' || side === 'SHORT') {
      row.getCell('side').font = { bold: true, size: BODY_FONT_SIZE, name: 'Calibri', color: { argb: LOSS_RED } };
    }

    // Right-align numeric columns
    ['quantity', 'entryPrice', 'exitPrice', 'fees', 'netPnl'].forEach(key => {
      row.getCell(key).alignment = { horizontal: 'right', vertical: 'middle' };
    });
  });

  // Freeze panes and auto-filter
  ledger.views = [{ state: 'frozen', xSplit: 2, ySplit: 3 }];
  ledger.autoFilter = {
    from: { row: 3, column: 1 },
    to: { row: 3, column: 11 },
  };

  // ===================================================================
  // SHEET 5: STRATEGY ANALYSIS
  // ===================================================================
  const strat = workbook.addWorksheet('Strategy Analysis');
  strat.properties.tabColor = { argb: INDIGO };

  strat.columns = [
    { header: 'Strategy Name', key: 'strategyName', width: 30 },
    { header: 'Trade Count', key: 'tradeCount', width: 15 },
    { header: 'Win Rate', key: 'winRate', width: 15 },
    { header: 'Net P&L', key: 'netPnl', width: 20 },
    { header: 'Average Trade', key: 'averageTrade', width: 20 },
    { header: 'Profit Factor', key: 'profitFactor', width: 15 },
  ];

  const stratBrand = strat.addRow(['ANNUAL COMPLIANCE REPORT — STRATEGY ANALYSIS']);
  applyBrandHeader(stratBrand, 30);
  strat.mergeCells('A1:F1');
  stratBrand.getCell(1).alignment = { horizontal: 'center', vertical: 'middle' };

  strat.addRow([]);

  const stratHeaderRow = strat.getRow(3);
  applySubHeader(stratHeaderRow, 6);

  if (data.strategies && data.strategies.length > 0) {
    data.strategies.forEach((s, idx) => {
      const row = strat.addRow({
        strategyName: s.strategyName || '',
        tradeCount: s.tradeCount || 0,
        winRate: (s.winRate || 0).toFixed(2) + '%',
        netPnl: s.netPnl || 0,
        averageTrade: s.averageTrade || 0,
        profitFactor: s.profitFactor === Infinity ? '∞' : (s.profitFactor || 0).toFixed(2),
      });

      styleDataRow(row, idx, 6);

      // Color Net P&L
      const net = s.netPnl || 0;
      row.getCell('netPnl').font = {
        bold: true,
        size: BODY_FONT_SIZE,
        name: 'Calibri',
        color: { argb: net >= 0 ? PROFIT_GREEN : LOSS_RED },
      };

      row.getCell('tradeCount').alignment = { horizontal: 'center', vertical: 'middle' };
      row.getCell('winRate').alignment = { horizontal: 'center', vertical: 'middle' };
      row.getCell('netPnl').alignment = { horizontal: 'right', vertical: 'middle' };
      row.getCell('averageTrade').alignment = { horizontal: 'right', vertical: 'middle' };
      row.getCell('profitFactor').alignment = { horizontal: 'center', vertical: 'middle' };
    });
  } else {
    const noDataRow = strat.addRow(['No strategy data available for the reporting period.']);
    strat.mergeCells('A4:F4');
    noDataRow.font = { italic: true, size: BODY_FONT_SIZE, name: 'Calibri', color: { argb: MEDIUM_GRAY } };
  }

  strat.views = [{ state: 'frozen', xSplit: 1, ySplit: 3 }];
  strat.autoFilter = {
    from: { row: 3, column: 1 },
    to: { row: 3, column: 6 },
  };

  // ===================================================================
  // SHEET 6: FINANCIAL SUMMARY
  // ===================================================================
  const finSum = workbook.addWorksheet('Financial Summary');
  finSum.properties.tabColor = { argb: NAVY };

  finSum.columns = [
    { width: 35 },
    { width: 25 },
  ];

  const finBrand = finSum.addRow(['ANNUAL COMPLIANCE REPORT — FINANCIAL SUMMARY']);
  applyBrandHeader(finBrand, 30);
  finSum.mergeCells('A1:B1');
  finBrand.getCell(1).alignment = { horizontal: 'center', vertical: 'middle' };

  finSum.addRow([]);

  addSectionHeader(finSum, 4, 'FINANCIAL METRIC');

  const finDataRows = [
    { label: 'Gross Profit', value: `$${(data.financialSummary.grossProfit || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}`, type: 'positive' },
    { label: 'Gross Loss', value: `($${(data.financialSummary.grossLoss || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })})`, type: 'negative' },
    { label: 'Net Profit', value: `$${(data.financialSummary.netProfit || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}`, type: data.financialSummary.netProfit >= 0 ? 'positive' : 'negative' },
    { label: 'Total Fees', value: `$${(data.financialSummary.totalFees || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}`, type: 'neutral' },
    { label: 'Net After Fees', value: `$${(data.financialSummary.netAfterFees || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}`, type: data.financialSummary.netAfterFees >= 0 ? 'positive' : 'negative' },
    { label: 'Average Trade', value: `$${(data.financialSummary.averageTrade || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}`, type: 'neutral' },
    { label: 'Profit Factor', value: data.financialSummary.profitFactor === Infinity ? '∞' : (data.financialSummary.profitFactor || 0).toFixed(2), type: 'neutral' },
    { label: 'Win Rate', value: `${(data.financialSummary.winRate || 0).toFixed(2)}%`, type: 'neutral' },
  ];

  const getColor = (type: string) => {
    switch (type) {
      case 'positive': return PROFIT_GREEN;
      case 'negative': return LOSS_RED;
      default: return NEUTRAL_BLUE;
    }
  };

  finDataRows.forEach((rowData, idx) => {
    const row = finSum.addRow([rowData.label, rowData.value]);
    styleDataRow(row, idx, 2);
    row.getCell(1).font = { bold: true, size: BODY_FONT_SIZE, name: 'Calibri', color: { argb: DARK_GRAY } };
    row.getCell(2).font = { bold: true, size: BODY_FONT_SIZE, name: 'Calibri', color: { argb: getColor(rowData.type) } };
    row.getCell(2).alignment = { horizontal: 'right', vertical: 'middle' };
    row.getCell(2).numFmt = '#,##0.00';
  });

  finSum.views = [{ state: 'frozen', xSplit: 0, ySplit: 4 }];

  // ===================================================================
  // SHEET 7: AUDIT TRAIL
  // ===================================================================
  const audit = workbook.addWorksheet('Audit Trail');
  audit.properties.tabColor = { argb: NAVY };

  audit.columns = [
    { width: 30 },
    { width: 60 },
  ];

  const auditBrand = audit.addRow(['ANNUAL COMPLIANCE REPORT — AUDIT TRAIL']);
  applyBrandHeader(auditBrand, 30);
  audit.mergeCells('A1:B1');
  auditBrand.getCell(1).alignment = { horizontal: 'center', vertical: 'middle' };

  audit.addRow([]);

  addSectionHeader(audit, 4, 'AUDIT ATTRIBUTE');

  const auditRows = [
    ['Export Timestamp', format(new Date(data.auditTrail.exportTimestamp), 'yyyy-MM-dd HH:mm:ss') + ' UTC'],
    ['Record Count', (data.auditTrail.recordCount || data.ledger.length).toString()],
    ['Account ID', data.auditTrail.accountId || 'N/A'],
    ['User ID', data.auditTrail.userId || 'N/A'],
    ['Export Version', data.auditTrail.exportVersion],
    ['Report ID', data.auditTrail.reportId],
    ['Data Source', data.auditTrail.dataSource],
    ['Record Created', data.auditTrail.recordCreationTimestamp ? format(new Date(data.auditTrail.recordCreationTimestamp), 'yyyy-MM-dd HH:mm:ss') : 'N/A'],
    ['Last Modified', data.auditTrail.recordModificationTimestamp ? format(new Date(data.auditTrail.recordModificationTimestamp), 'yyyy-MM-dd HH:mm:ss') : 'N/A'],
  ];

  auditRows.forEach((rowData, idx) => {
    const row = audit.addRow(rowData);
    styleDataRow(row, idx, 2);
    row.getCell(1).font = { bold: true, size: BODY_FONT_SIZE, name: 'Calibri', color: { argb: DARK_GRAY } };
  });

  audit.views = [{ state: 'frozen', xSplit: 0, ySplit: 4 }];

  // ===================================================================
  // SHEET 8: DATA INTEGRITY
  // ===================================================================
  const di = workbook.addWorksheet('Data Integrity');
  di.properties.tabColor = { argb: INDIGO };

  di.columns = [
    { width: 35 },
    { width: 70 },
  ];

  const diBrand = di.addRow(['ANNUAL COMPLIANCE REPORT — DATA INTEGRITY']);
  applyBrandHeader(diBrand, 30);
  di.mergeCells('A1:B1');
  diBrand.getCell(1).alignment = { horizontal: 'center', vertical: 'middle' };

  di.addRow([]);

  addSectionHeader(di, 4, 'INTEGRITY ATTRIBUTE');

  const diRows = [
    ['SHA-256 Hash', data.dataIntegrity.sha256Hash || 'N/A'],
    ['Checksum', data.dataIntegrity.checksum || 'N/A'],
    ['Record Verification Count', (data.dataIntegrity.recordVerificationCount || 0).toString()],
    ['Generation Timestamp', data.dataIntegrity.generationTimestamp ? format(new Date(data.dataIntegrity.generationTimestamp), 'yyyy-MM-dd HH:mm:ss') + ' UTC' : 'N/A'],
  ];

  diRows.forEach((rowData, idx) => {
    const row = di.addRow(rowData);
    styleDataRow(row, idx, 2);
    row.getCell(1).font = { bold: true, size: BODY_FONT_SIZE, name: 'Calibri', color: { argb: DARK_GRAY } };
    // Allow text wrap for long hashes
    row.getCell(2).alignment = { wrapText: true, vertical: 'middle' };
  });

  di.views = [{ state: 'frozen', xSplit: 0, ySplit: 4 }];

  return workbook;
}